apiVersion: v1
kind: Service
metadata:
  name: healthz
  namespace: platform-demo
spec:
  selector:
    app.kubernetes.io/name: healthz
  ports:
    - name: http
      port: 80
      targetPort: http
